# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

# Starship modules
[character]
success_symbol = "[[󰄛](green) ❯](mauve)"
error_symbol = "[[󰄛](red) ❯](mauve)"
vimcmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode

[username]
show_always = true
style_user = "bold mauve"

[git_branch]
style = "bold mauve"
symbol = " "

[git_status]
style = "bold mauve"
stashed = "≡"

[git_commit]
tag_symbol = "  "

[directory]
truncation_length = 10
truncation_symbol = ".../"
style = "bold mauve"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Palette definition
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[c]
symbol = " "

[lua]
symbol = " "

[os.symbols]
Arch = " "

[python]
symbol = " "

[scala]
symbol = " "
